package ostosrekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ostosrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.08.03 13:51:22 // Generated by ComTest
 *
 */
public class OstosrekisteriTest {
    //ComTestin tekosia



  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Ostosrekisteri: 35
    Ostosrekisteri ostosrekisteri = new Ostosrekisteri(); 
    Ostos ostos1 = new Ostos(); Ostos ostos2 = new Ostos(); 
    ostos1.rekisteroi(); ostos2.rekisteroi(); 
    assertEquals("From: Ostosrekisteri line: 40", 0, ostosrekisteri.getOstokset()); 
    ostosrekisteri.lisaa(ostos1); 
    assertEquals("From: Ostosrekisteri line: 42", 1, ostosrekisteri.getOstokset()); 
    ostosrekisteri.lisaa(ostos2); 
    assertEquals("From: Ostosrekisteri line: 44", 2, ostosrekisteri.getOstokset()); 
  } // Generated by ComTest END
}