package ostosrekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ostosrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.08.03 13:51:12 // Generated by ComTest
 *
 */
public class OstosTest {



  // Generated by ComTest BEGIN
  /** testToString145 */
  @Test
  public void testToString145() {    // Ostos: 145
    Ostos testiostos = new Ostos(); 
    testiostos.parse("  4 |  Pirkka Olut |  1.0  | 12 | 12.00 | 3 | 8 | 2011"); 
    assertEquals("From: Ostos line: 148", 4, testiostos.getOstosnumero()); 
    assertEquals("From: Ostos line: 149", true, testiostos.toString().startsWith("4|Pirkka Olut|1.0|12|")); 
    Ostos testiostos2 = new Ostos(); 
    testiostos2.parse(" 19 | Porkgalia | 2.0 | 5 | 10.00 | 5 | 2 | 2009"); 
    assertEquals("From: Ostos line: 153", 19, testiostos2.getOstosnumero()); 
    assertEquals("From: Ostos line: 154", true, testiostos2.toString().startsWith("19|Porkgalia|2.0|5|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse170 */
  @Test
  public void testParse170() {    // Ostos: 170
    String testirivi1 = "5|Kalja|1.00|1|1.00|7|7|2015"; 
    String testirivi2 = "6|Porkkana|0.70|2|1.40|6|6|2006"; 
    Ostos testiostos1 = new Ostos(); 
    Ostos testiostos2 = new Ostos(); 
    testiostos1.parse(testirivi1); 
    assertEquals("From: Ostos line: 177", 5, testiostos1.getOstosnumero()); 
    testiostos1.toString().startsWith("5|Kalja|1.00|1|1.00|7|7|2015"); 
    testiostos2.parse(testirivi2); 
    assertEquals("From: Ostos line: 181", 6, testiostos2.getOstosnumero()); 
    testiostos2.toString().startsWith("6|Porkkana|0.70|2|1.40|6|6|2006"); 
  } // Generated by ComTest END
}